# Generated by Django 4.2.7 on 2023-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warriors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="race",
            field=models.CharField(
                choices=[("s", "student"), ("d", "developer"), ("t", "teamlead")],
                default=1,
                max_length=1,
                verbose_name="Расса",
            ),
            preserve_default=False,
        ),
    ]
