# Generated by Django 4.2.7 on 2023-11-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warriors", "0002_warrior_race"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warrior",
            name="race",
        ),
    ]
