# Generated by Django 4.2.5 on 2023-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board', '0003_remove_answer_submitted_at_answer_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
