# Generated by Django 4.2.5 on 2023-10-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board', '0004_alter_answer_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='student',
        ),
    ]
